[[authirized_apps]]
  app_id = "test_app"
  name = "test_app"
  secret = "62fda0f2212eaffd90dbf04136768c5f"
  method = "any"
  timeout = 0
  open_api = "/gatekeeper"
  white_ips = ""
  city_ids = ""
  total_query_daily = 1000000
  qps = 2
  group_id = 0

[[authirized_apps]]
  app_id = "test_app2"
  name = "test_app2"
  secret = "f851a26357dd0dc1da58f21a172288be"
  method = "any"
  timeout = 0
  open_api = "/gatekeeper/data_service/ping"
  white_ips = ""
  city_ids = ""
  total_query_daily = 0
  qps = 0
  group_id = 0
