# This is base config

[base]
    debug_mode="debug"                  # debug or release, debug会打印gin的接口列表
    access_log="on"                     # on or off 是否打印请求日志，default "on"
    time_location="Asia/Chongqing"
    conf_load_interval = 300000         # 配置自动刷新时间

[http]
    route_prefix = "/gatekeeper"        # 所有对外服务的route前缀, 如：/gateway
    addr =":8081"                       # 监听地址, default ":8700"
    req_host = "100.90.164.31"              # 绑定请求地址
    read_timeout = 30                   # 读取超时时长
    write_timeout = 30                  # 写入超时时长
    max_header_bytes = 20               # 最大的header大小，二进制位长度

#集群配置
[cluster]
    cluster_ip ="127.0.0.1"             # 集群地址,对外提供服务的地址
    cluster_addr =":8081"               # http监听端口
    cluster_list ="127.0.0.1"           # 集群子机器ip,多ip以逗号分隔

#请求日志
[log]
    log_level = "trace"                 #日志打印最低级别
    [log.file_writer]                   #文件写入配置
        on = true
        log_path = "./logs/didi.log"
        rotate_log_path = "./logs/didi.log.%Y%M%D%H"
        wf_log_path = "./logs/didi.log.wf"
        rotate_wf_log_path = "./logs/didi.log.wf.%Y%M%D%H"
    [log.console_writer]                #工作台输出
        on = false
        color = false

#系统日志
[syslog]
    log_level = "trace"             #日志打印最低级别
    [syslog.file_writer]            #文件写入配置
        on = true
        log_path = "./logs/syslog.log"
        rotate_log_path = "./logs/syslog.log.%Y%M%D%H"
        wf_log_path = "./logs/syslog.log"
        rotate_wf_log_path = "./logs/syslog.log.%Y%M%D%H"
    [syslog.console_writer]
        on = false
        color = false

#检查日志
[checklog]
    log_level = "trace"             #日志打印最低级别
    [checklog.file_writer]          #文件写入配置
        on = true
        log_path = "./logs/checklog.log"
        rotate_log_path = "./logs/checklog.log.%Y%M%D%H"
        wf_log_path = "./logs/checklog.log"
        rotate_wf_log_path = "./logs/checklog.log.%Y%M%D%H"
    [checklog.console_writer]
        on = false
        color = false

#统计日志
[statlog]
    log_level = "trace"             #日志打印最低级别
    [statlog.file_writer]           #文件写入配置
        on = true
        log_path = "./logs/statlog.log"
        rotate_log_path = "./logs/statlog.log.%Y%M%D%H"
        wf_log_path = "./logs/statlog.log"
        rotate_wf_log_path = "./logs/statlog.log.%Y%M%D%H"
    [statlog.console_writer]
        on = false
        color = false
