[[module]]
  [module.base]
    load_type = "http"
    name = "test_http"
    service_name = "test_http"
    pass_auth_type = 2
    frontend_addr = ""

  [[module.match_rule]]
    type = "url_prefix"
    rule = "/gatekeeper/test_http"
    rule_ext = ""
    url_rewrite = "^/gatekeeper/test_http(.*) $1,^/gatekeeper/test_2http(.*) $1"

  [[module.match_rule]]
    type = "url_prefix"
    rule = "/gatekeeper/test_2http"
    rule_ext = ""
    url_rewrite = "^/gatekeeper/test_http(.*) $1,^/gatekeeper/test_2http(.*) $1"
  [module.load_balance]
    check_method = "httpchk"
    check_url = "/ping"
    check_timeout = 2000
    check_interval = 5000
    type = "round-robin"
    ip_list = "127.0.0.1:8081"
    weight_list = "50"
    forbid_list = ""
    proxy_connect_timeout = 10001
    proxy_header_timeout = 10002
    proxy_body_timeout = 10003
    max_idle_conn = 200
    idle_conn_timeout = 10004
  [module.access_control]
    black_list = ""
    white_list = ""
    white_host_name = ""
    auth_type = ""
    client_flow_limit = 0
    open = 1

[[module]]
  [module.base]
    load_type = "tcp"
    name = "test_tcp"
    service_name = "test_tcp"
    pass_auth_type = 2
    frontend_addr = ":8900"

  [[module.match_rule]]
    type = "url_prefix"
    rule = ""
    rule_ext = ""
    url_rewrite = ""
  [module.load_balance]
    check_method = "tcpchk"
    check_url = ""
    check_timeout = 2000
    check_interval = 5000
    type = "round-robin"
    ip_list = "127.0.0.1:8018"
    weight_list = "50"
    forbid_list = ""
    proxy_connect_timeout = 10001
    proxy_header_timeout = 0
    proxy_body_timeout = 0
    max_idle_conn = 0
    idle_conn_timeout = 0
  [module.access_control]
    black_list = ""
    white_list = ""
    white_host_name = ""
    auth_type = ""
    client_flow_limit = 0
    open = 1

[[module]]
  [module.base]
    load_type = "http"
    name = "shoping_service"
    service_name = "shoping_service"
    pass_auth_type = 2
    frontend_addr = ""

  [[module.match_rule]]
    type = "url_prefix"
    rule = "/gatekeeper/shoping_service"
    rule_ext = ""
    url_rewrite = "^/gatekeeper/test_service(.*) $1"
  [module.load_balance]
    check_method = "httpchk"
    check_url = "/ping"
    check_timeout = 2000
    check_interval = 5000
    type = "round-robin"
    ip_list = "127.0.0.1:8701"
    weight_list = "100"
    forbid_list = ""
    proxy_connect_timeout = 10000
    proxy_header_timeout = 10000
    proxy_body_timeout = 10000
    max_idle_conn = 100
    idle_conn_timeout = 10000
  [module.access_control]
    black_list = ""
    white_list = ""
    white_host_name = ""
    auth_type = ""
    client_flow_limit = 0
    open = 0

[[module]]
  [module.base]
    load_type = "tcp"
    name = "test_tcp23"
    service_name = "test_tcp23"
    pass_auth_type = 2
    frontend_addr = ":8800"

  [[module.match_rule]]
    type = "url_prefix"
    rule = ""
    rule_ext = ""
    url_rewrite = ""
  [module.load_balance]
    check_method = "tcpchk"
    check_url = ""
    check_timeout = 2000
    check_interval = 5000
    type = "round-robin"
    ip_list = "127.0.0.1:8701"
    weight_list = "100"
    forbid_list = ""
    proxy_connect_timeout = 10000
    proxy_header_timeout = 0
    proxy_body_timeout = 0
    max_idle_conn = 0
    idle_conn_timeout = 0
  [module.access_control]
    black_list = "192.168.0.1,192.168.0.2"
    white_list = "127.0.0.1,127.0.0.1"
    white_host_name = "ipd-cloud-preweb00.gz01"
    auth_type = ""
    client_flow_limit = 0
    open = 1
